spring.application.name=loganalyzer
# Allow React to send massive log files without the server crashing
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# We will put your actual Gemini AI Key here later
gemini.api.key=YOUR_API_KEY_HERE